### ISSUE TITLE
Investigate smaller base images

### ISSUE THREAD

**Issue by Webreaper** [Webreaper/Damselfly-Base-Image#3]
https://github.com/Webreaper/Damselfly/issues/378
https://github.com/Webreaper/Damselfly/issues/390

**Comment by stumpylog** [comment]
Just stumbled across this, is there a reason the build tools are left in the final image?  The main image doesn't appear to build anything, and removing things like `build-essential` and the build-deps for each tool could make a big difference in the size of the image.  Just an idea to investigate.  Right now, the building of ImageMagik leaves 1.2GB in the final image.

**Comment by Webreaper** [comment]
Thanks. Good idea - I'll take a look!

**Comment by Webreaper** [comment]
Tried it in dev, but it only seems to knock about 100MB off the final image size. It's not nothing, but.... (I'm confused as to your '1.2GB' comment, given that the base image is only 700MB or so....)

**Comment by stumpylog** [comment]
The command `docker history` can give you an idea of what each layer of the image is added to the final size reported by `docker image ls`.  

One thing to keep in mind is that changes made in one layer do not affect things added in another layer.  So executing a cleanup step in a new `RUN` directive does not end up reducing the image size.  That's because docker uses an overlay file system.

**Comment by stumpylog** [comment]
I would do something like this:
```Dockerfile
WORKDIR /home/

COPY [ \
  "make_imagemagick.sh", \
  "make_exiftool.sh", \
  "cleanup.sh", \
  "/home/" \
]

RUN set -eux \
  && ls -ahl \
  && chmod +x ./make_imagemagick.sh \
  && /home/make_imagemagick.sh \
  && chmod +x ./make_exiftool.sh \
  && /home/make_exiftool.sh \
  && ./cleanup.sh \
  && /home/cleanup.sh
```

And then iterate on the cleanup to remove more items installed via `apt-get build-dep -y imagemagick` which grabs a whopping amount of packages

**Comment by Webreaper** [comment]
Ah, if course. So doing a single cleanup at the end won't help. I'll put one in each of the two scripts that do the build layers.

Thanks for the tips!

**Comment by Webreaper** [comment]
Okay, that seems to have helped - base image size looks to have dropped by about 30%. :)

**Comment by Izumiko** [comment]
I tried the multistage build method (#6 ), and the image size has clearly reduced.

**Comment by Webreaper** [comment]
Will take a look. Thanks. 

Did you validate that all of the AI stuff still works? (I can check).

**Comment by Izumiko** [comment]
I haven't validated it yet, I only tested Exiftool and ImageMagick in validate.sh

**Comment by Webreaper** [comment]
Oh, cool. That should be good enough. (I missed this was the base image -
will do some tests and release!)

**Comment by Webreaper** [comment]
Merged - will build a dev version of Damselfly using this image and check it all works!

**Comment by Webreaper** [comment]
Hey, @Izumiko, I had a small problem - when the image builds within github actions, the extraction of the downloaded libheif tarball fails: 
```
0.225 gzip: stdin: unexpected end of file
0.226 tar: Child returned status 1
0.226 tar: Error is not recoverable: exiting now
```
See: https://github.com/Webreaper/Damselfly-Base-Image/actions/runs/12552037571/job/34997406327#step:7:3919

I'm not a tar expert, so wasn't sure what's going on; wondering if perhaps this gz file is in an odd tar format or something. So instead I reverted back to git-clone, which seems to work (but per your changes, I'm pulling an explicit tag, rather than just checking out main). If you have any idea what the tar command issue is, let me know.

I think this works, will try using it in a Damselfly build now!

**Comment by Izumiko** [comment]
I overlooked the `-L` parameter; the GitHub download URL returns a 302 status code, so we need `-L` to follow the redirect.
correct code:
```
RUN cd /home && mkdir libheif && curl -L https://github.com/strukturag/libheif/releases/download/v${LIBHEIF_VERSION}/libheif-${LIBHEIF_VERSION}.tar.gz | tar zx -C libheif --strip-components 1 \
```

BTW, the `make_exiftool.sh` script is no longer necessary, so you can remove it. The `Dockerfile-CmdLineTool` also appears to be outdated. Should we consider updating it or removing it as well?

**Comment by Webreaper** [comment]
Cool, sounds good. Will investigate those other cleanups.
